### ISSUE TITLE
Hawtio 2.3.0 not working with Spring-boot 2.0.3 ".yml"

### ISSUE THREAD

**Issue by gamebaboo** [hawtio/hawtio#2554]
It didn't work Hawtio Web Console.

When i used ".properties" file, It works.

What's the difference?

1. yml
`camel:
  springboot:
    name: SampleCamel

server:
  port: 10000

management:
  server:
    port: 10001
  endpoints:
    web:
      exposure:
        include: hawtio, jolokia

hawtio:
  authenticationEnabled: false
`

2. properties
`server.port=10000
management.server.port=10001

management.endpoints.web.exposure.include=hawtio,jolokia

camel.springboot.name=SampleCamel
timer.period=10000
hawtio.authenticationEnabled=false
`

**Comment by alexkieling** [comment]
What do you mean by "not working"? Can you provide an error message? I've converted [application.properties](https://github.com/hawtio/hawtio/blob/master/examples/springboot/src/main/resources/application.properties) to YAML and it worked fine.

**Comment by alexkieling** [comment]
/home/akieling/dev/projects/hawtio/hawtio/examples/springboot/src/main/resources/application.yml

**Comment by alexkieling** [comment]
```
server:
  port: "10000"
management:
  server:
    port: "10001"
  endpoints:
    web:
      exposure:
        include: hawtio,jolokia
logging:
  level:
    io:
      hawt: INFO
      undertow: WARN
    org:
      springframework: WARN
camel:
  springboot:
    name: SampleCamel
timer:
  period: "10000"
hawtio:
  authenticationEnabled: "false"
```
