### ISSUE TITLE
Hawtio.io 2.4.0. Spring-boot with Jhipster

### ISSUE THREAD

**Issue by assimbly** [hawtio/hawtio#2559]
I have a [JHipster](https://www.jhipster.tech/) generated web application which uses Spring Boot 2.0.7. I have added the hawtio spring boot dependency to the build file. Then I add the jolokia and hawtio to the management endpoints in the application.yml:

```yaml
management:
    endpoints:
        web:
            base-path: /management
            exposure:
                include: ["configprops", "env", "health", "info", "threaddump", "logfile", "hawtio", "jolokia"]
hawtio:
  authenticationEnabled:  false 
```

In the Spring security I granted access to both pages. Now I can access the /management/jolokia page (this returns a json respone). I can also access jolokia from a standalone Hawtio console. However when I use the embedded hawtio console the page won't load.

In the Java console I see this on start up:

2018-12-31 00:30:06.193  INFO 3640 --- [  restartedMain] io.hawt.HawtioContextListener            : Initialising hawtio services
2018-12-31 00:30:06.193 DEBUG 3640 --- [  restartedMain] io.hawt.system.ConfigManager             : Failed to look up environment context: Need to specify class name in environment or system property, or as an applet parameter, or in an application resource file:  java.naming.factory.initial
2018-12-31 00:30:06.193  INFO 3640 --- [  restartedMain] io.hawt.system.ConfigManager             : Configuration will be discovered via system properties
2018-12-31 00:30:06.193  INFO 3640 --- [  restartedMain] io.hawt.jmx.JmxTreeWatcher               : Welcome to Hawtio 2.4.0

This when accessing the page:

2018-12-31 12:54:49.674 DEBUG 3884 --- [ XNIO-2 task-12] io.hawt.web.auth.SessionExpiryFilter     : Accessing [/management/hawtio], hawtio path is []

In the browser console I only see some warnings:

Loading <script> with source ‘http://localhost:8080/management/app/polyfills.bundle.js’ failed. hawtio:12:1
Loading <script> with source ‘http://localhost:8080/management/app/main.bundle.js’ failed. hawtio:12:1
Loading <script> with source ‘http://localhost:8080/management/app/global.bundle.js’ failed.  

It seems that Jhipster wants to load/redirect to its own pages? Anyone got this working with latest Jhipster?

Note:
 
By default authenticationEnabled is set to true with realm karaf. I would expect the webcontainer configuration with its default settings (authenticationEnabled =false and realm="*"). When setting the parameter "authenticationEnabled" is true, I see the Hawtio login screen.
