### ISSUE TITLE
Hawtio inaccessible in Spring Boot on separate management port with auth disabled

### ISSUE THREAD

**Issue by creckord** [hawtio/hawtio#2623]
I have hawtio configured in a Spring Boot app with the following configuration (excerpt):

```
spring:
  jmx:
    enabled: true
management:
  endpoints:
    enabled-by-default: true
    web:
      base-path: /
      exposure:
        include: "hawtio,jolokia"
  server:
    port: 9990
    servlet:
      context-path: /
```

Running the app, I can access http://localhost:9990/hawtio and see the hawtio login page. Good. But for testing purposes, since I do not have any users configured, I wanted to disable the login with

```
hawtio:
  authenticationEnabled: false
```

However, now http://localhost:9990/hawtio just shows my main app's entry page - the same as http://localhost:8080 (without redirect, though).
