### ISSUE TITLE
Hawtio not honoring "x-forwarded-prefix" header

### ISSUE THREAD

**Issue by tonyfalabella** [hawtio/hawtio#2704]
Version io.hawt:hawtio-springboot:2.13.5 does not seem to be honoring "x-forwarded-prefix" headers.  

We have a Spring Boot application deployed on a kubernetes cluster with configuration like below
```
apiVersion: extensions/v1beta1  
kind: Ingress  
metadata:
  name: myservice
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/x-forwarded-prefix: "/myservice"
    nginx.ingress.kubernetes.io/ssl-passthrough: "true"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
spec:
  rules:
    - host: ${cluster-host}
      http:
        paths:
          - path: /myservice(/|$)(.*)
            backend:
              serviceName: myservice
              servicePort: 443
  tls:
    - hosts:
        - ${cluster-host}
```
application.yml contains:
```
management:
  endpoint:
    hawtio:
      enabled: true
    jolokia:
      enabled: true
```
When attempting to visit the actuator endpoint the `actuator\hawtio` page does not load because the redirects/forwards don't seem to be honoring the x-forwarded-prefix.
