### ISSUE TITLE
Browser got `Permissions policy violation: Synchronous requests are disabled by permissions policy` error with ActiveMQ artemis

### ISSUE THREAD

**Issue by win5923** [hawtio/hawtio#3456]
Hi, 
I'm encountering some issues while trying to expose the activemq artemis console to the outside.

When I use the following Istio `gateway` and `virtualService` for routing:

```yaml
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: activemq-gateway
  namespace: activemq-artemis-operator
spec:
  selector:
    istio: ingressgateway
  servers:
    - port:
        number: 80
        name: http
        protocol: HTTP
      hosts:
      - "*"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: activemq-web-virtualservice
  namespace: activemq-artemis-operator
spec:
  gateways:
    - activemq-gateway
  hosts:
    - "*"
  http:
  - match:
    - uri:
        prefix: /
    route:
      - destination:
          host: artemis-broker-wconsj-0-svc
          port:
            number: 8162
```

DevTools shows: `[Violation] Permissions policy violation: Synchronous requests are disabled by permissions policy.`
![image](https://github.com/hawtio/hawtio/assets/56353753/5e4cc9ce-40e7-4157-af69-47d246346e9a)
```
[hawtio-core] Failed loading script: " Failed to execute 'send' on 'XMLHttpRequest': Failed to load 'http://x.x.x.x/artemis-plugin/plugin/js/artemisHelpers.js?_=1716344301188'. " (<a href=" /artemis-plugin/plugin/js/artemisHelpers.js : undefined "> /artemis-plugin/plugin/js/artemisHelpers.js
[hawtio-core] Failed loading script: " Failed to execute 'send' on 'XMLHttpRequest': Failed to load 'http://x.x.x.x/artemis-plugin/plugin/js/artemisPlugin.js?_=1716344301189'. " (<a href=" /artemis-plugin/plugin/js/artemisPlugin.js : undefined "> /artemis-plugin/plugin/js/artemisHelpers.js
...
```

Using the Kubernetes port-forwarding feature, the browser displays the content normally.
![image](https://github.com/artemiscloud/activemq-artemis-operator/assets/56353753/63c4f7e7-4899-461f-8405-2fdf4647da0d)

Any idea would be greatly appreciated!

---edited---
ActiveMQArtemis config:
```yaml
apiVersion: broker.amq.io/v1beta1
kind: ActiveMQArtemis
metadata:
  name: artemis-broker
  namespace: activemq-artemis-operator
spec:
  resourceTemplates:
    - selector:
        kind: "StatefulSet"
      patch:
        kind: "StatefulSet"
        spec:
          template:
            spec:
              initContainers:
              - name: "artemis-broker-container-init"
                volumeMounts:
                - name: jolokia-access
                  mountPath: /opt/amq/bin/launch.sh
                  subPath: launch.sh
                  readOnly: true
              volumes:
              - name: jolokia-access
                configMap:
                  name: artemis-jolokia-access
                  items:
                    - key: launch.sh
                      path: launch.sh
                      mode: 0755

  acceptors:
    - name: activemq-mqtt
      expose: false
      port: 5672
      protocols: mqtt
      sslEnabled: true
      sslSecret: amq-ssl-secret

  console:
    expose: true
    exposeMode: ingress
    ingressHost: artemis-broker-console.test.com

  
  deploymentPlan:
    size: 1
    initImage: quay.io/artemiscloud/activemq-artemis-broker-init:artemis.2.33.0
    image: quay.io/artemiscloud/activemq-artemis-broker-kubernetes:artemis.2.33.0
    journalType: nio

    # image: placeholder
    enableMetricsPlugin: true
    containerSecurityContext:
      runAsNonRoot: true
  env:
    - name: AMQ_EXTRA_ARGS
      value: "--relax-jolokia"
    - name: AMQ_REQUIRE_LOGIN
      value: "true"
    - name: JAVA_ARGS_APPEND
      value: -Dwebconfig.bindings.artemis.uri=http://0.0.0.0:8161
```
